services:
  db:
    image: mysql
    container_name: mysql-295-project-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build:
      context: ./backend
    image: chatbox-backend:1.0
    depends_on:
    - db
    environment:
      MYSQL_HOST: db
    ports:
    - "8080:8080"
volumes:
  db_data:
